sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
- docker build -t probot-hello .
script:
- docker run -it --rm probot-hello npm run test
- docker run -it --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: ILHW/avcbv715mCbL40bajTfJ78W3HH9iiH6mj73/5KY2bcQHU+1quqFBR0BpKGgMSvd3cKeTVwiKfjsOSjEXKTmYYYiyzj5tYXmjpYjMOyhnWnfs54afdpLWyO8Idghw8nyz2BY2WPXNjK5vxmusD7eGNwpHFqUbCQ3FXrXQq+Nah99+/QMZ4gJ4H1/hdeXxaj+TwIcRr5YOQxtpykxpZSVM3djZTowmTM5iSCQ3k8+Ukq1uvux/av+p4r1jH7uNWzzN6+FPSMYEEpyu+hOQPU8hHmRd0a9GZU+Iyh30WojQdTdqnYk8KYNPHG5R8GMMAIHWTyUNwJ/RB+FnmCW7ClxmiCQDDh/bizYt0vRAyi7xQlsMq1qVRklyXguSR4dIhx5Xmye0IsjNt13K0iE/Yhom0Yigv1TnJffuhuSVh758wv928Q1U/kqNpautmxtjORhdXxuw3UrnG2czYGEPbRCcPe/GQnnkgiN9+ZDndJ5fxxoRLwgNfr+xpTiGxsymr98p/F9xBudYRMguZonrvadPFLQDojpAdPf80f5jWkofA9wHMZjBAwJU06ok/ics2ANdDaxCGbDVGkBZyKnegg/rfTQpegRx5H2sFhzxMYbty119rqVXACo+gHa7eliOhQ968+KFIOBkTfD9aDtAUw6o317/bHM5EKclwH91HY=
  on: heroku_production
  app: probot-tzairos
