sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
- docker built -t probot-hello .
script:
- docker run -it --rm probot-hello npm run test
- docker run -it --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: bmLhKKDOIosBvWmiMaem+PMyC2lzIdJdPWBWrn6Bd+xx4suwP22LUVtHT4Y+V6qKzaRgl3Tr814sR7EygHrXFcW6BZj9WM4my84bFx9+JtLHX5Cc5d7G+Puso0ZjJWUBI63umtf90mPNT9ZRIN90wC3y7EAywlwjkrRZbblZv6qcg2ZmLaFmYloQo2/jFcfcVQHEg5utFJya3z/tQY6EkSUoFTGiQ4VmXLQYee6WIJNWLBkQcyZfBQ3KVR/ifi1OxcwTCH5EtN5fUK6XxXoiro84SrNtkYO2xpKISnfQlSccMMq0UjXDAxpq/Z9tJWGyYyyCg5Dndxv/P1Up/5ISKWyPjtITsixe4zGNaEkXOaqKMyqXycOR3Lf1CKNj0JNq11FgyX/yBmdh5MAFANyqms6EOOtHfqmrHg3I33Kn4JTxexPGbIVpV+7kOCw/ZMgLYvp8ZHpVrMg7ZEmC98SrnLPnMn//u6208TKQaVID1fCOAP0DMARbLimI2gW9jlz6axzbV4Ohen+Xgo6TmC+dJrs/RpN0XUhhtJPX/Zy1cJeWtR4l0o+hLWNyj4DbrioP3wfCBs1OKyNSGS3Y2jlN7rt+EXSokblUAXIVSeSi3rI0L7YfeBXLL0e17CvB2YKCe9+PVe7RjluQYbVWlgSf8y6wN0tUb65KHlhzyXHo6gg=
  on: heroku_production
  app: probot-tzairos

